version: "2"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: hippo
      POSTGRES_USER: hippo
      POSTGRES_PASSWORD: hippo
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  hippo-app:
    build: .
    depends_on:
      - db
    environment:
      PORT: 4000
      DB_HOST: db
      DB_USER: hippo
      DB_PASS: hippo
      DB_NAME: hippo

    ports:
      - 4000:4000
    links:
      - db
