version: "2"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: hippo
      POSTGRES_USER: hippo
      POSTGRES_PASSWORD: hippo
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
